---

  - name: Install Prerequisites for Debian
    apt: >
      name={{ item }}
      state=installed
    with_items:
      - build-essential
      - python-dev
      - libevent-dev
      - python-setuptools #easy_install
      - liblzma-dev
      - libssl-dev
      - swig
    sudo: yes

  # We must install pip before we can use the pip module below
  - easy_install: name=pip #state=latest required ansible 2.x
    sudo: yes

  - name: Install and Configure Docker Registry
    pip:
      name: docker-registry
      extra_args: "{{pip_extra_args}}"
    sudo: yes

  - file: path={{docker.registry.home}} state=directory

  - name: copy docker-registry configuration file
    copy: src=config.yml dest=/usr/local/lib/python2.7/dist-packages/config/config.yml
    sudo: yes
    notify: restart docker-registry

  - file: path=/var/log/docker-registry state=directory
    sudo: yes

  - copy: src=docker-registry.conf dest=/etc/init/
    sudo: yes
    notify: restart docker-registry

  - name: ensure Docker Registry is started
    service: name=docker-registry state=started
    sudo: yes

  - name: Secure Docker Registry with Nginx for Debian
    apt: >
      name={{item}}
      state=installed
    with_items:
      - nginx
      - python-passlib
      - openssl
    sudo: yes

  - file: path=/etc/nginx/certs state=directory
    sudo: yes
    when: docker.registry.with_ssl|bool

  - name: stat docker-registry certificate file
    stat: path=/etc/nginx/certs/{{docker.registry.host}}.crt
    register: docker_registry_cert_stat
    when: docker.registry.with_ssl|bool

  - name: create server key and certificate
    include: certificate.yml
    when: docker.registry.with_ssl|bool and (not docker_registry_cert_stat.stat.exists)
    notify: restart nginx

  - htpasswd: path=/etc/nginx/docker-registry.htpasswd name={{item.name}} password={{item.password}} owner=root group=root mode=0644
    with_items: docker.registry.users
    sudo: yes
    notify: restart nginx

  - copy: src=nginx-docker-registry.conf dest=/etc/nginx/docker-registry.conf
    sudo: yes
    notify: restart nginx

  - template: src=docker-registry.j2 dest=/etc/nginx/sites-available/docker-registry owner=root group=root mode=0644
    sudo: yes
    notify: restart nginx

  - file: src=/etc/nginx/sites-available/docker-registry dest=/etc/nginx/sites-enabled/docker-registry state=link
    sudo: yes
    notify: restart nginx
