- name: 'Restart jenkins'
  become: True
  service:
    name: "{{ jenkins_service_name }}"
    state: 'restarted'

- name: 'Waiting jenkins started'
  uri:
    url: "{{ jenkins_base_url }}/"
    status_code: '200,403'
  register: 'jenkins_check_available'
  until: "(jenkins_check_available.status == 200)
             or (jenkins_check_available.status == 403)"
  retries: "{{ jenkins_waiting_available_retries }}"
  delay: "{{ jenkins_waiting_available_delay }}"
  changed_when: False 