---

- name: 'Check if Jenkins v2 default administrative password file exists'
  become: True
  stat:
    path: "{{ jenkins_default_adm_passd_file }}"
  register: 'jenkins_administrative_password_file_test'
  changed_when: False 

- name: 'Jenkins 2.0 default password protection workaround'
  include: "{{ role_path }}/tasks/utils/jenkins_password_workaround.yml"
  register: 'jenkins_authentication_disabled'
  when:
    - "jenkins_administrative_password_file_test.stat.exists is defined"
    - "jenkins_administrative_password_file_test.stat.exists" 

- name: restart jenkins
  include: "{{role_path}}/tasks/utils/restart-jenkins.yml"

- name: 'Copy Groovy scripts'
  become: True
  copy:
    src: "{{ role_path }}/files/groovy_scripts"
    dest: "{{ jenkins_etc_home_location }}/"
    owner: "{{ jenkins_etc_user }}"
    group: "{{ jenkins_etc_group }}"
    mode: '0640'  


- include: config-jenkins-docker.yml

- include: config-jenkins-plugin.yml

