---

- name: ensure centos-extras repository is enabled
  command: yum-config-manager --enable extras
  become: yes

- name: uninstall older versions of Docker
  yum: 
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine
  become: yes

- name: install the required packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: yes

- name: setup the stable repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: install docker-ce
  yum:
    name: "docker-ce-{{docker.version}}.ce"
    state: present
  become: yes

- name: Enable Docker service on boot and Start it
  service: name=docker enabled=yes state=restarted
  become: yes
