---

- name: uninstall older versions of Docker
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  become: yes

#- name: Install packages to allow apt to use a repository over HTTPS
#  apt:
#    name: "{{item}}"
#    state: present
#    update_cache: yes
#  with_items:
#    - apt-transport-https
#    - ca-certificates
#    - curl
#    - software-properties-common
#  become: yes

- name: copy Docker's official GPG key
  copy: 
    src: ubuntu.gpg
    dest: /tmp/

- name: add Docker's official GPG key
  apt_key:
    file: /tmp/ubuntu.gpg
    state: present
  become: yes

- name: install Docker's stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
  become: yes

- name: install docker-ce
  apt:
    name: "docker-ce={{docker.version}}~ce-0~ubuntu"
    state: present
    update_cache: yes
  become: yes
